name: same_type_streams_builder
description: A builder widget for multiple streams of the same type.
version: 0.1.0
homepage: https://github.com/alexeyinkin/flutter-same-type-streams-builder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
